USEPA/EPATADA

vignettes/WQPDataHarmonization.Rmd
These are just recommendations...
Summary: "=" to "<-" and added spaces around "=" in variable assignment.
These recommendations  can be found in the tidyverse style guide: https://style.tidyverse.org/
I recommend using the tidyverse style guide because it is comprehensive, actively maintained, and widely used throughout the R community.
It may be helpful to add the lintr package to your development workflow: https://lintr.r-lib.org/
=> I recommend using the tidyverse style guide

R/DataDiscoveryRetrieval.R, man/TADAdataRetrieval.Rd, tests/testthat/test-DataDiscoveryRetrieval.R, vignettes/WQPDataHarmonization.Rmd
Removed donttest/ from example for now. If we submit to CRAN eventually, this may need to be brough back in. I think this should fix the current check error
=> removed donttest

R/ResultFlagsDependent.R
Check for at least one IS NOT NaN value in column before proceeding, addresses [Issue #137](https://github.com/USEPA/TADA/issues/137).
=> DepthProfileData Fix issue #137

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, R/ResultFlagsDependent.R
Current commits should resolve issue [#137](https://github.com/USEPA/TADA/issues/137). Wait to merge as I'll make at least two additional commits (one for some refactoring, one to drop branch checks), putting this in now to make sure it passes checks on develop branch (passes locally and on fork).
=> Depth profile data

vignettes/CONTRIBUTING.Rmd, vignettes/WQPDataHarmonization.Rmd
Made some minor grammar corrections as a GitHub test run.
=> Vignettes proofreading kh

R/Filtering.R, R/ResultFlagsDependent.R, R/ResultFlagsIndependent.R, R/Transformations.R
Added examples to functions in ResultFlagsDependent.R, ResultFlagsIndependent.R, Transformations.R (except HarmonizeCensoredData and CensoredDataStats), and Filtering.R.
This addresses issue #126 (but does not close it).
=> Added examples to completed functions

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/pr-commands.yaml, .github/workflows/style-and-lint.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, man/PotentialDuplicateRowID.Rd
=> automated workflows

DESCRIPTION, R/Utilities.R
Can you take a look and let me know if anything looks wonky? I ran the tests and devtools::check() and everything seems fine, but would like another set of eyes!
=> Char ranges eh

R/Tables.R, R/Transformations.R, man/TADA_CalculateTotalNP.Rd
small edits to flag content and added results from summations.
=> Small summation tweaks

DESCRIPTION, R/Figures.R
=> add button to reset zoom on overview map

R/Figures.R, man/TADA_OverviewMap.Rd
Dynamic site radii (based on quantiles) for measurements for TADA_OverviewMap
=> 297 dynamic site radii based on dataset

R/Filtering.R, R/RequiredCols.R, man/TADA_AnalysisDataFilter.Rd
I simplified the function (removed multiple time consuming joining steps), updated some of the language in the documentation (removing any lingering mentions of assessments), set clean = FALSE as the default, added TADA_OrderCols() to end of function and added TADA.UseForAnalysis.Flag to the list of required columns.
Do my changes adequately address the issue(s) you observed?
=> 402 tada analysisdatafilter bug

R/Figures.R
Fix for "Can't display both discrete & non-discrete data on same axis" by using as.Date() on ActivityStartTime before plotting. I also added y = -0.2 in the legend positioning so legend won't appear on top of x axis labels.
=> Scatterplot issues

vignettes/TADAR5.Rmd
a few small text updates. trying to fix 2 characteristic scatterplot issue
=> R5 package demo

R/DataDiscoveryRetrieval.R, man/TADA_BigDataRetrieval.Rd, man/TADA_DataRetrieval.Rd
- Adds countrycode filter to TADA_DataRetrieval
- Adds countrycode, statecode, countycode, organization to TADA_BigDataRetrieval
- Updated documentation for both
=> 344 data retrieval updates

vignettes/TADAAssessmentUnitUseCase.Rmd, vignettes/TADAModule1.Rmd
Very small changes from review
=> Rmd review

R/DepthProfile.R
Title is centered and does not overlap with plot.
=> 476 tada depthprofileplot title overlaps plot

R/ResultFlagsDependent.R, vignettes/TADAWaterSciConWorkshopDemo.Rmd
New vignette for water sci con workshop.
=> Nm vignette

R/Figures.R, R/Utilities.R, man/TADA_GroupedScatterplot.Rd
Created a for loop for TADA_GroupedScatter to condense the code and make it more concise. Will work to edit other functions like TADA_DepthProfilePlot to see if this can be done there
TADA_ViewColorPalette() should also return a stored value in the example documentations now rather than return NULL or an empty list().
=> Figures.r condensed code and tada view color palette to return a non null value

vignettes/articles/NMCWorkshop.Rmd
I just whacked this together - @mhweber -- can you run it through and make sure this makes sense for this audience? I can make mods as needed.
=> blodgett contribution to workshop
